### ISSUE TITLE
Request toggle to enable/disable generation of connecting lines

### ISSUE THREAD

**Issue by golanlevin** [CreativeInquiry/PEmbroider#103]
For people working with plotters (such as the AxiDraw), it would be good to have an explicit toggle to include or disclude the generation and export of "connecting lines" (lines between graphical objects). We already have the `toggleResample()` function, which helpfully eliminates intermediate stitches; this is the other piece of that puzzle. Also, please add to documentation :)

**Comment by golanlevin** [comment]
Looking at this image, the toggle would need to remove both the red lines, as well as the spurious black ones...is that possible? 

![PEmbroider_optimize_per_char](https://user-images.githubusercontent.com/290053/93166086-bb661b80-f6eb-11ea-91ea-db7253fee096.png)

**Comment by LingDong-** [comment]
Yup, I'm going do it by littering every place with a conditional

```java
if (! dont_connect){ /* do things that might produce connecting lines*/ }
```

**Comment by LingDong-** [comment]
Feature added: d4ac5bf14835460f72ab112e29372c7d6effa7c2

```java
E.toggleConnectingLines(false);

```
