### ISSUE TITLE
SVG Export leave connecting lines between shapes

### ISSUE THREAD

**Issue by danzeeeman** [CreativeInquiry/PEmbroider#107]
SVG Export leave connecting lines between shapes

<img width="1612" alt="Screen Shot 2021-08-24 at 3 17 43 PM" src="https://user-images.githubusercontent.com/719564/130807847-0b72f1bc-09f5-4d71-80da-a69babc1ff38.png">

<img width="2032" alt="Screen Shot 2021-08-24 at 3 00 18 PM" src="https://user-images.githubusercontent.com/719564/130807856-e1742023-9efd-4a05-a8e8-fd713ebdee0a.png">

**Comment by golanlevin** [comment]
@danzeeeman,  I had recalled there being a solution for this, and there is; it's just currently undocumented. @LingDong- says: 
> _To make SVG output skip the connecting lines, you can either pass noConnect to PEmbroider.write, or set NO_CONNECT to true._ 

This is implemented here: 
* https://github.com/CreativeInquiry/PEmbroider/blob/master/src/processing/embroider/PEmbroiderWriter.java#L2326
* https://github.com/CreativeInquiry/PEmbroider/blob/master/src/processing/embroider/PEmbroiderGraphics.java#L126
